export enum RootScreens {
  MAIN = "Main",
  WELCOME = "Welcome",
  ONBOARDING = "ONBOARDING",
  LOGIN = "LOGIN",
  HOMESCREEN = "HOMESCREEN",
  STATISTICS = "STATISTICS",
  PLAN = "PLAN",
  USER = "USER",
  ADDTRANSACTION = "ADDTRANSACTION",
  EDITTRANSACTION = "EDITTRANSACTION",
  CHOOSECATEGORY = "CHOOSECATEGORY",
  EDITCHOOSECATEGORY = "EDITCHOOSECATEGORY",
}
